# Generated by Django 4.2.3 on 2023-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plan_status_team_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stripe_subscription_id',
        ),
    ]
