# Generated by Django 4.2.2 on 2023-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('medium', 'medium'), ('low', 'Low'), ('high', 'High')], default='low', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('won', 'Won'), (' contacted', 'Contacted'), ('lost', 'Lost'), ('inprogress', 'In progress')], default='new', max_length=25),
        ),
    ]
