# Generated by Django 4.2.2 on 2023-08-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'medium')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('lost', 'Lost'), (' contacted', 'Contacted'), ('inprogress', 'In progress'), ('won', 'Won')], default='new', max_length=25),
        ),
    ]
