# Generated by Django 4.2.3 on 2023-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'medium')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(' contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost'), ('won', 'Won'), ('new', 'New')], default='new', max_length=25),
        ),
    ]
