# Generated by Django 4.2.3 on 2023-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'medium'), ('low', 'Low')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('won', 'Won'), ('new', 'New'), ('lost', 'Lost'), ('inprogress', 'In progress'), (' contacted', 'Contacted')], default='new', max_length=25),
        ),
    ]
